### ISSUE TITLE
Linking issues for nightly torch on iOS

### ISSUE THREAD

**Issue by PCerles** [pytorch/ios-demo-app#11]
Hi, I followed the tutorial at https://pytorch.org/mobile/ios/#xcode-setup.

I cloned the torch Github repo and checked out the "nightly" branch.

`SELECTED_OP_LIST=model.yaml BUILD_PYTORCH_MOBILE=1 IOS_ARCH=arm64 ./scripts/build_ios.sh`
Then copied the static library and headers into the PyTorchDemo directory
`cp -r build_ios/install /path/toPyTorchDemo/`
Then added this to "Other Linker Flags"
`-force_load $(PROJECT_DIR)/install/lib/libtorch.a`
Then added this to "Header Search Paths"
`$(PROJECT_DIR)/install/include/`
I also disabled Bitcode. 
I also had to switch `"include LibTorch/LibTorch.h"` to be "include `"torch/script.h"` in `TorchModule.mm`
However, when I try and build the project I get linking issues, e.g.
`Undefined symbol: typeinfo for c10::AutogradMetaInterface`
Am I missing a step here?

**Comment by xta0** [comment]
Did you add `torch::autograd::AutoGradMode guard(false);` before running forward?

**Comment by PCerles** [comment]
Yes but these errors are in the linking stage
`ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by PCerles** [comment]
Okay I was able to solve this by adding all of the of the libraries generated in install/lib to XCode in "Other Linker Flags"
-force_load $(PROJECT_DIR)/install/lib/libtorch.a -force_load $(PROJECT_DIR)/install/lib/libtorch_cpu.a -force_load $(PROJECT_DIR)/install/lib/libc10.a -force_load $(PROJECT_DIR)/install/lib/libclog.a -force_load $(PROJECT_DIR)/install/lib/libcpuinfo.a -force_load $(PROJECT_DIR)/install/lib/libeigen_blas.a -force_load $(PROJECT_DIR)/install/lib/libnnpack.a -force_load $(PROJECT_DIR)/install/lib/libpytorch_qnnpack.a

**Comment by xta0** [comment]
> Okay I was able to solve this by adding all of the of the libraries generated in install/lib to XCode in "Other Linker Flags"
> `-force_load $(PROJECT_DIR)/install/lib/libtorch.a -force_load $(PROJECT_DIR)/install/lib/libtorch_cpu.a -force_load $(PROJECT_DIR)/install/lib/libc10.a -force_load $(PROJECT_DIR)/install/lib/libclog.a -force_load $(PROJECT_DIR)/install/lib/libcpuinfo.a -force_load $(PROJECT_DIR)/install/lib/libeigen_blas.a -force_load $(PROJECT_DIR)/install/lib/libnnpack.a -force_load $(PROJECT_DIR)/install/lib/libpytorch_qnnpack.a `

You can also do `-all_load`

**Comment by PCerles** [comment]
@xta0 where does the all_load flag go? I can't figure out the proper link command here
