### ISSUE TITLE
The operation couldn’t be completed. (PyTorchDemo.-CameraController.CameraControllerError error 1.)

### ISSUE THREAD

**Issue by MarkLyubimov** [pytorch/ios-demo-app#15]
Hello!

I was trying to run pytorch demo app for image classification and got this error: "The operation couldn’t be completed. (PyTorchDemo.-CameraController.CameraControllerError error 1.)". 
I don't have any swift experience so could you please help me fix it?

What could be the reason?

Thank you!

PS. It worked for NLP part.

![image](https://user-images.githubusercontent.com/36645303/79385476-51491f00-7f71-11ea-97da-eaf3cdf7ca9d.png)

**Comment by ValentinRicher** [comment]
It does not work when testing on the Simulator but if you push the app on your iPhone it actually works. To do so, follow this great tutorial https://codewithchris.com/deploy-your-app-on-an-iphone/

**Comment by MarkLyubimov** [comment]
Now it works, thank you!

**Comment by ValentinRicher** [comment]
Don't forget to close the issue
