### ISSUE TITLE
Both apps crash in release mode!

### ISSUE THREAD

**Issue by harshthaker** [pytorch/ios-demo-app#23]
PyTorch: 1.4.0
LibTorch: 1.4.0
iOS 13.5
XCode 11.5

Trying to deploy PyTorch model in iOS app. It works okay when I run it in debug mode. Model shows results. On changing to release mode, the app crashes.
Even running both tutorial apps "HelloWorld" and "PyTorchDemo" tend to **crash in release mode**.

`#11	0x00000001035f95f4 in torch::jit::script::Module::forward(std::__1::vector<c10::IValue, std::__1::allocator<c10::IValue> >) /ios-demo-app-master/PyTorchDemo/Pods/LibTorch/install/include/torch/csrc/jit/script/module.h:113`

Here's is the function in module.h:

```
 IValue forward(std::vector<IValue> inputs) {
    return get_method("forward")(std::move(inputs)); //breaks here
  }
```

**Comment by xta0** [comment]
Duplicated with - https://github.com/pytorch/ios-demo-app/issues/22
