### ISSUE TITLE
XNNPACK.a not arm64,  is macOS

### ISSUE THREAD

**Issue by xiaoqiangsheng2016** [pytorch/ios-demo-app#29]
build HelloWord project with mobile device, is error with libXNNPACK.a file built for macOS, not architecture arm64

https://github.com/google/XNNPACK.git

XNNPACK platform  only has macOS or android, not iOS, how can I slove this problem?

**Comment by husthyc** [comment]
Please refer to https://github.com/pytorch/pytorch/issues/44143#issuecomment-701703075.
