### ISSUE TITLE
Add example of how to optimize model for mobile inference

### ISSUE THREAD

**Issue by mirth** [pytorch/ios-demo-app#3]
This demo is great and works fine although it would be great to have an example of how to prepare model for mobile inference cause it's non trivial. For example you can add the receipt of how you've prepare the `mobilenet_quantized.pt`.
(Personally i've tried to convert my model to `float16` (it didn't work: model didn't load on mobile), also i've tried `torch.quantization.quantize` and it also didn't work.
Tnx!

**Comment by xta0** [comment]
cc @supriyar

**Comment by supriyar** [comment]
Thanks for your feedback @mirth!

The preparation of quantized model for mobile is the same as for server. The quantized MobileNetV2 model is based on this tutorial: https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html 

The quantized mobile backend is set during model load, which is currently already being by the iOS app.

**Comment by RYYAI** [comment]
hi supriyar. The quantized model used in this project is the quantized model of aware training or per_channel_quantized_model?

**Comment by supriyar** [comment]
I believe the model used in this example is the result of quantization aware training using per-tensor quantization.
