### ISSUE TITLE
Build issue HelloWorld app

### ISSUE THREAD

**Issue by oplatek** [pytorch/ios-demo-app#4]
Hi!

I cannot compile the example app.
I may have overlooked something obvious since I am new to iOS development.

I downloaded and saved the model to `ios-demo-app/HelloWorld/HelloWorld/HelloWorld/model/model.pt`
I run `pod install` from `ios-demo-app/HelloWorld/HelloWorld`.

Then I opened the xcode project and the build failed:

Thank you for helping me!

<img width="1182" alt="Screenshot 2019-10-30 at 12 36 21" src="https://user-images.githubusercontent.com/229266/67855491-d1d6a900-fb12-11e9-986d-0b1a1983e902.png">

Xcode version: 11.1
MacOS: 10.15

**Comment by xta0** [comment]
Did you open the TestApp.xcodeproj or `TestApp.xcworkspace`? If you installed the library via cocoapods, you should open `TestApp.xcworkspace`.
