### ISSUE TITLE
Object Detection link broken

### ISSUE THREAD

**Issue by ShreshthSaxena** [pytorch/ios-demo-app#44]
"Object Detection demonstrates how to convert the popular YOLOv5 model and use it on an iOS app that detects objects from pictures in your photos, taken with camera, or with live camera."

The readme file mentions a demonstration of Yolov5 on iOS but the link seems to be broken

Is there a demo on Yolov5 conversion for iOS yet ?

**Comment by xta0** [comment]
@jeffxtang Could you help take a took at this issue?

**Comment by jeffxtang** [comment]
@ShreshthSaxena did you mean the model download link? You can request access to download the model, before it's replaced with another link that anyone with the link can download.

Or maybe you refer to the link to the iOS Object Detection demo app? It's been fixed.
