### ISSUE TITLE
let module = TorchModule(fileAtPath: filePath) failed

### ISSUE THREAD

**Issue by QinZiwen** [pytorch/ios-demo-app#47]
```
pip install torchvision
python trace_model.py
pod install
```

work well, but when I select an iOS simulator and launch it, "let module = TorchModule(fileAtPath: filePath)" failed to run. I can be sure that filePath is right.

thanks

**Comment by xta0** [comment]
@jeffxtang  could you help take a look?

**Comment by jeffxtang** [comment]
@QinZiwen what's the error message you got?

**Comment by QinZiwen** [comment]
@jeffxtang @xta0 thanks
It was found that CUDA was set when the model was exported. After deletion, everything was normal

**Comment by CarlosModinez** [comment]
@QinZiwen could you explain what did you do? I'm struggling with the same problem. 
Thanks
