### ISSUE TITLE
 Fatal error: Failed to load model!

### ISSUE THREAD

**Issue by monica3-3** [pytorch/ios-demo-app#50]
I was deploying the official code in ios-demo-app/ObjectDetection on my iPhone(ios 14.0). 

I have copied the result of the export.py (yolov5s.torchscript.pt) to the ios-demo-app/ObjectDetection/ObjectDetection folder. Then It was built successfully but when I tried to run the model, this error occured to me.

Same error happened when I tried the ios-demo-app/PytorchDemo code. I am wondering if 'Bundle.main.path' can correctly open this .pt file. 

<img width="867" alt="WeChat388030beb7d97de3e6f42d09cb5fd50e" src="https://user-images.githubusercontent.com/69756119/113581592-e8632700-9659-11eb-9e57-61756476e8e9.png">

**Comment by JorgeCeja** [comment]
Hey @monica3-3 please post your solution here as a reference? Thanks!

**Comment by MatoMA** [comment]
> Hey @monica3-3 please post your solution here as a reference? Thanks!

@JorgeCeja https://github.com/pytorch/android-demo-app/issues/132 

In Podfile:
Change
pod 'LibTorch', '~>1.7.0'
to
pod 'LibTorch', '~>1.8.0'

pod install

Worked for me

**Comment by SajjadAemmi** [comment]
Edit Podfile:
‍‍‍```
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ObjectDetection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjectDetection
  pod 'LibTorch-Lite', '~>1.12.0'
end
```
Worked for me
