### ISSUE TITLE
cocoapods can not download v0.0.2

### ISSUE THREAD

**Issue by Lisajoy512** [pytorch/ios-demo-app#6]
hi, our project require the minimum deploy target is 10.0, so we want to download the v0.0.2.But we can not pod install successfully and can not reach the source https://ossci-ios.s3.amazonaws.com/libtorch_ios_0.0.2.zip

**Comment by xta0** [comment]
@Lisajoy512 There is no v0.0.2. PyTorch mobile started with v1.3.0, and we just released v1.3.1. I think what you can do is compiling the PyTorch from source code. See https://pytorch.org/mobile/ios/#build-pytorch-ios-libraries-from-source for details.

**Comment by xta0** [comment]
I'm going to close this issue. Feel free to reopen it if you still have questions
