### ISSUE TITLE
Memory Leak for PyTorchDemo with Metal

### ISSUE THREAD

**Issue by lamhoangtung** [pytorch/ios-demo-app#68]
Hi, I'm trying to create a demo Image Classification app from the PyTorchDemo Image Classification code that run on the GPU with Metal. By referencing the HelloWorld-Metal and various PyTorch documentation, I did some modification:

Change the `Podfile` to this:
```cocapod
platform :ios, '14.3'
target 'PyTorchDemo' do
  pod 'LibTorch-Lite-Nightly'
end
```
And run `pod update`

Then I changed `TorchBridge/TorchModule.mm` to this:
```objectivec
#import "TorchModule.h"
#import <LibTorch-Lite-Nightly/LibTorch-Lite.h>

@implementation TorchModule {
 @protected
  torch::jit::mobile::Module _impl;
}

- (nullable instancetype)initWithFileAtPath:(NSString*)filePath {
  self = [super init];
  if (self) {
    try {
      c10::InferenceMode mode;
      _impl = torch::jit::_load_for_mobile(filePath.UTF8String);
    } catch (const std::exception& exception) {
      NSLog(@"%s", exception.what());
      return nil;
    }
  }
  return self;
}

@end

@implementation VisionTorchModule

- (NSArray<NSNumber*>*)predictImage:(void*)imageBuffer {
  try {
      float* floatBuffer;
      {
        c10::InferenceMode mode;
        torch::autograd::AutoGradMode guard(false);
        at::Tensor tensor = torch::from_blob(imageBuffer, {1, 3, 256, 256}, at::kFloat).metal();
        auto outputTensor = _impl.forward({tensor}).toTensor().cpu();
        floatBuffer = outputTensor.data_ptr<float>();
      }
    if (!floatBuffer) {
      return nil;
    }
    NSMutableArray* results = [[NSMutableArray alloc] init];
    for (int i = 0; i < 12; i++) {
      [results addObject:@(floatBuffer[i])];
    }
    
    return [results copy];
  } catch (const std::exception& exception) {
    NSLog(@"%s", exception.what());
  }
  return nil;
}

@end
```
Which move the input tensor to the GPU with that `.metal()` call and move the result to the CPU with that `.cpu()` call. Noted that my input size `{1, 3, 256, 256}` and num classes `12` is a bit different from the original example. 

The app compile fine and run fine on my iPhone 7 test device, by looking at the debug tab on XCode I can see that the GPU are indeed working, but I notice a constant increase in memory consumption overtime

![image](https://user-images.githubusercontent.com/26834698/132479835-7017b08d-914a-4a00-bd28-35396c1a22c2.png)

Which does not happen with the original CPU only code.

By using the Instrument tool in XCode, I can pin point what memory are being leaks:
![image](https://user-images.githubusercontent.com/26834698/132480133-185541bd-3f0a-49df-83c6-e33ce148eeb7.png)

Some of them are:
```
MPSCNNAdd	203	< multiple >	88,81 KiB	PyTorchDemo	at::Tensor at::native::metal::binaryElementwiseMPSCNNKernel<MPSCNNAdd>(at::Tensor const&, at::Tensor const&)
MPSImage	52	< multiple >	8,94 KiB	PyTorchDemo	at::native::metal::createStaticImage(c10::ArrayRef<long long>)
MPSCNNPoolingAverage	26	< multiple >	8,53 KiB	PyTorchDemo	at::native::metal::adaptive_avg_pool2d(at::Tensor const&, c10::ArrayRef<long long>)
```
Which indeed come from torch mobile. The full leak report for that fews second run can be downloaded from [here](https://drive.google.com/file/d/1378UjuVRaXLlyo5WWq4LhM2rryXBcTLu/view?usp=sharing)

I've tried using another mobilenetv2 model that was exported from torchvision but the problem still persist. Since I'm not really familiar with Swift and Objective C, I've been searching for way to delete or dereference object that I think might be get stuck behind like the input and output tensor, for ex: create separate scope, set the object to null but none had work yet.

Are there any thing that I am doing wrong here ? Any help is appreciated ;(

Thanks for checking by ;)

**Comment by HieuNT1998** [comment]
chuc em may man :))

**Comment by xta0** [comment]
@lamhoangtung  Thanks for the reporting, we'll look into this.

**Comment by husthyc** [comment]
@lamhoangtung what model were you using at first. I noticed that the model in PyTorch Demo is mobilenet_quantized.pt which are:
1. it is a quantized model which is not able to run on GPU now.
2. it is a full-jit model which is not able to run with the lite-interpreter runtime

**Comment by lamhoangtung** [comment]
Hi @husthyc. Actually I just rename my model to `mobilenet_quantized.pt` so it can works without any code changes. The model that I use is simply a resnet18 that you can get by runnning this:

**Comment by husthyc** [comment]
@lamhoangtung The root cause is that the ARC was not enabled when building PyTorch iOS. A fix is coming out.

**Comment by lamhoangtung** [comment]
Thanks for the great news @husthyc <3

**Comment by xta0** [comment]
@lamhoangtung fix has been landed on master. Can you try the latest nightly build?

**Comment by lamhoangtung** [comment]
Thanks @xta0 and @husthyc for the help. I have tried `LibTorch-Lite-Nightly 1.11.0.20211106 (was 1.10.0.20210906)` and the problem had been fixed. No more memory leak ;)
